<?php
define('OAUTH_KEY','');
define('OAUTH_SECRET','');
define('OAUTH_KEY_GET',OAUTH_KEY);
define('OAUTH_SECRET_GET',OAUTH_SECRET);
define('BASE_URL','');
define('API_VERSION','1.1');
define('DEBUG',FALSE);
define('DOLOG',FALSE);
define('COMPRESS',FALSE);
define('O_MODE_PARSE_ENTITIES',FALSE);
?>
